# Generated by Django 5.2.4 on 2025-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_payment_amount_alter_payment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
