# Generated by Django 5.2.4 on 2025-09-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
