# Generated by Django 5.2.4 on 2025-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_tag_alter_payment_amount_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='default_product.png', null=True, upload_to='products/'),
        ),
    ]
