# Generated by Django 5.2.4 on 2025-09-12 12:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dtssxxfra/image/upload/v1757684769/default_product_o2hcxg.png', max_length=255, null=True, verbose_name='products/'),
        ),
    ]
