# Generated by Django 5.2.4 on 2025-09-12 13:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='products'),
        ),
    ]
