# Generated by Django 5.2.4 on 2025-11-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe')], max_length=50),
        ),
    ]
